### PR TITLE
Save System, Information Puzzle, Outlined walls & Bugfixes

### LINKED ISSUE #52: TorchController not working
# What is going on?
Mainpath lighting won't work after switching levels.

# What should happen?
The mainpath lighting should work every time.

# Steps to reproduce
1. Go ingame
2. Go into a level
3. Get to the next level (how is irrelevant)
4. Toggle the mainpath lighting
5. Observe the torches not lighting up

### LINKED ISSUE #53: NextLevel not working
# What is going on?
Clicking "next level" is not working

# What should happen?
"Next level" should initiate the next level.

# Steps to reproduce
1. Go ingame
2. Complete a level
3. Click on "next level"
4. Observe nothing happening

### LINKED ISSUE #54: "Levelauswahl" not saving state
# What is going on?
When going from ingame to the "Levelauswahl", the game state is not being saved thus when going back undefined behavior will occur.

# What should happen?
When going to "Levelauswahl" and back ingame, the game should be in the same state as before.

# Steps to reproduce
This is not reproduceable as the "back" button is not implemented yet.

### LINKED ISSUE #55: "Back" button in "Levelauswahl" not working correctly
# What is going on?
The "back" button in "Levelauswahl" is pointing to "Hauptmenü", always.

# What should happen?
The "back" button in "Levelauswahl" should guide the player back ingame.

# Steps to reproduce
1. Go ingame
2. Hit "esc" 
3. Go to "Levelauswahl"
4. Hit "back"
5. Observe the "Hauptmenü" popping up.

### LINKED ISSUE #56: AI Pathfinding bad in Level1
# Fix
Will be fixed in #48

### LINKED ISSUE #57: Player can play any level, always
# What is going on?
The player can play any level at any point.

# What should happen?
The player should only be able to play level n, if they had completed level n-1 beforehand.

# Steps to reproduce
1. Go ingame
2. Hit "play"
3. Observe you can choose from any level

### PR DESCRIPTION
**Pull request by leonlaas**
# List of changes
## Additions 
- Information Puzzle (Currently has "BlueTorch", "Vase" and "Chest" as Information Types)
- PuzzleDone event
- outline to Walls
- theme Font
- Grey-out for levels beyond the next level
- Save System

## Changes
- Improved UI (Main Menu, Level done, Levelauswahl)
- Moved and renamed all Puzzle related stuff to more sensible names

## Bugfixes
- Closes #56 
- Closes #55 (Current implementation: "Back" Button is only visible when coming from ingame)
- Closes #54 
- Closes #53 
- Closes #57 
- Maybe closes #52 
- Fixed PuzzleDone trigger direction being illogical

## Known Bugs in this PR
- A TON of Audio related errors/crashes

image

image
I know it looks like shit but it's what they want.

### CODE REVIEW

**Review by krumbs8749 — APPROVED** [review]

**Comment by cr4yfish** [comment]
'EventEmitter' can only be present once per scene -> Each 'PuzzeObject' has to commit to a Quiz on 'onEnable()'.

**Comment by cr4yfish** [comment]
All Puzzle are completely broken right now @leonlaas .

**Comment by cr4yfish** [comment]
At some point #52 broke again :(

**Comment by cr4yfish** [comment]
At some point #52 broke again :(

**Comment by cr4yfish** [comment]
I opened it for review, since this PR is feature-complete.

**Comment by cr4yfish** [comment]
image

**Pull request merged**
